### ISSUE TITLE
Unable to view network when exported from Cytoscape v3.2.1

### ISSUE THREAD

**Issue by ategge** [idekerlab/cy-net-share#13]
I exported a network using Cytoscape v3.2.1 into a .cyjs file per directions on the ReadMe of the GitHub page. When I try to load the network into CyNetShare, no network is displayed. My cyjs file is located at http://bioinformatics.cs.vt.edu/~ategge/misc/temp.cyjs

**Comment by keiono** [comment]
Hi.

Currently, cyNetShare simply renders original location of nodes.  Your temp.cyjs file does not contains any (x,y) locations.  To avoid this, you can export your network from Cytoscape by selecting File-->Export --> Network and view.  Then you can select cyjs as its file format.

**Comment by ategge** [comment]
Thank you for the clarification.
